-- Shared SQLite/PostgreSQL schema. Versioned by schema_migrations.
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,recovery TEXT NOT NULL,role TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0,balance BIGINT NOT NULL DEFAULT 0,held BIGINT NOT NULL DEFAULT 0,created_at TEXT NOT NULL,CHECK(balance>=held AND held>=0));

CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,expires BIGINT NOT NULL,agent TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS auth_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,until_time BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS pricing(version BIGINT PRIMARY KEY,body TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS quotes(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),body TEXT NOT NULL,expires BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS charges(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),quote_id TEXT UNIQUE NOT NULL REFERENCES quotes(id),request_key TEXT NOT NULL,project_id TEXT NOT NULL,amount BIGINT NOT NULL,state TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(user_id,request_key));

CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,delta BIGINT NOT NULL,held_delta BIGINT NOT NULL,balance_after BIGINT NOT NULL,held_after BIGINT NOT NULL,reference TEXT UNIQUE NOT NULL,note TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,detail TEXT NOT NULL,created_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,body TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS ledger_user ON ledger(user_id,created_at);

CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
