export type Shot = {
  id: string;
  title: string;
  chapter: string;
  description: string;
  camera: string;
  prompt: string;
  caption: string;
  transition: string;
  duration: number;
  editSeconds: number;
  timelineStart: number;
  status: string;
  taskId?: string;
  attempt: number;
  videoUrl?: string;
  thumbnailUrl?: string;
  error?: string;
};
export type Asset = {
  id: string;
  name: string;
  role: 'bride' | 'groom' | 'reference' | 'music';
  url: string;
  file: string;
  mime: string;
  providerAssetId?: string;
};
export type Project = {
  id: string;
  title: string;
  brief: string;
  duration: number;
  style: string;
  ratio: string;
  status: string;
  progress: number;
  message: string;
  synopsis: string;
  demo: boolean;
  shots: Shot[];
  assets: Asset[];
  events: { at: string; message: string }[];
  filmUrl?: string;
  posterUrl?: string;
  outputResolution?: string;
  createdAt: string;
  updatedAt: string;
  revision: number;
  generatedSeconds: number;
  generationBudget: number;
  llmModel?: string;
  videoModel?: string;
};
export type StudioConfig = {
  connected: boolean;
  llmModel: string;
  videoModel: string;
  maxDuration: number;
  generationConcurrency: number;
};
