export type Shot = {
  id: string;
  title: string;
  chapter: string;
  description: string;
  camera: string;
  prompt: string;
  caption: string;
  transition: string;
  entryAction?: string;
  exitAction?: string;
  transitionReason?: string;
  duration: number;
  editSeconds: number;
  timelineStart: number;
  status: string;
  taskId?: string;
  attempt: number;
  videoUrl?: string;
  thumbnailUrl?: string;
  error?: string;
  actId?: string;
  lookId?: string;
  changeToLookId?: string;
  factIds?: string[];
  cueIds?: string[];
  imagePrompt?: string;
};
export type Asset = {
  id: string;
  name: string;
  role: 'bride' | 'groom' | 'reference' | 'music' | 'person' | 'product';
  url: string;
  file: string;
  mime: string;
  providerAssetId?: string;
};
export type Project = {
  wedding?: WeddingWorkflow;
  creationMode?: string;
  templateId?: string;
  templateVersion?: string;
  scene?: string;
  ownerId?: string;
  autoTitle?: boolean;
  id: string;
  title: string;
  brief: string;
  duration: number;
  style: string;
  ratio: string;
  status: string;
  progress: number;
  message: string;
  synopsis: string;
  demo: boolean;
  shots: Shot[];
  assets: Asset[];
  events: { at: string; message: string }[];
  filmUrl?: string;
  posterUrl?: string;
  outputResolution?: string;
  createdAt: string;
  updatedAt: string;
  revision: number;
  generatedSeconds: number;
  generationBudget: number;
  llmModel?: string;
  videoModel?: string;
  promptPolicy?: string;
  generationMode?: string;
  musicSections?: {
    name: string;
    start: number;
    end: number;
    instruments: string;
    energy: number;
    chapter?: string;
    prompt?: string;
    accent?: string;
    join?: string;
  }[];
  musicCues?: {
    id: string;
    start: number;
    end: number;
    prompt: string;
    taskId?: string;
    file?: string;
    status?: string;
  }[];
  musicSource?: string;
  musicFile?: string;
  musicUrl?: string;
  occasion?: string;
  customPrompt?: string;
  voiceoverScript?: string;
  voiceDirection?: string;
  wardrobeMode?: string;
  wardrobePrompt?: string;
  endingText?: string;
  treatment?: {
    concept: string;
    identityAnchor: string;
    openingHook: string;
    closingLine: string;
    musicDirection: string;
    bpm: number;
    mustHave: string[];
    avoid: string[];
    notes: string[];
    looks: { id: string; name: string; bride: string; groom: string }[];
    acts: {
      id: string;
      title: string;
      lookId: string;
      setting: string;
      storyBeat: string;
      bridge: string;
      music?: string;
      firstShot: number;
      lastShot: number;
      start: number;
      end: number;
    }[];
  };
};

export type WeddingArtifact = {
  id: string;
  kind: string;
  name: string;
  file: string;
  url: string;
  mime: string;
  sha256: string;
  bytes: number;
  shotId?: string;
  text?: string;
};
export type WeddingStep = {
  number: number;
  name: string;
  status: string;
  version: string;
  artifacts: WeddingArtifact[];
  approvals: {
    by: string;
    actorId: string;
    evidence: string;
    at: string;
    version: string;
  }[];
};
export type WeddingWorkflow = {
  automatic?: boolean;
  policyVersion: string;
  currentStep: number;
  completed: boolean;
  steps: WeddingStep[];
  narrationUrl?: string;
  narrationSeconds?: number;
  cues?: { id: string; start: number; end: number; text: string }[];
  subtitleUrl?: string;
};
export type StudioConfig = {
  connected: boolean;
  baseUrl: string;
  llmModel: string;
  videoModel: string;
  audioModel?: string;
  apiKeySet?: boolean;
  apiKeyHint?: string;
  maxDuration: number;
  generationConcurrency: number;
  styles?: {
    id: string;
    name: string;
    description: string;
    bpm: number;
    shotsPerMinute: number;
    direction: string;
    music: string;
  }[];
};
